repos:

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.7
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
      exclude: ^(docs/|tests)
    - id: ruff-format

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.6
  hooks:
  - id: codespell
    args: ["--toml", "pyproject.toml"]
    additional_dependencies: ["tomli"]

# - repo: https://github.com/pycqa/pydocstyle
#   rev: 6.1.1
#   hooks:
#   - id: pydocstyle
#     additional_dependencies: [toml]
#     exclude: "tests/"

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-merge-conflict
  - id: debug-statements
  - id: trailing-whitespace
  - id: no-commit-to-branch
    args: [--branch, main]
  - id: requirements-txt-fixer

# this validates our github workflow files
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.28.2
  hooks:
    - id: check-github-workflows
