# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alex/source/pyacvd

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alex/source/pyacvd

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alex/source/pyacvd/CMakeFiles /home/alex/source/pyacvd//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alex/source/pyacvd/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named clustering

# Build rule for target.
clustering: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clustering
.PHONY : clustering

# fast build rule for target.
clustering/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clustering.dir/build.make CMakeFiles/clustering.dir/build
.PHONY : clustering/fast

#=============================================================================
# Target rules for targets named nanobind-static

# Build rule for target.
nanobind-static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nanobind-static
.PHONY : nanobind-static

# fast build rule for target.
nanobind-static/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/build
.PHONY : nanobind-static/fast

home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/common.o: home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/common.cpp.o
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/common.o

# target to build an object file
home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/common.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/common.cpp.o
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/common.cpp.o

home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/common.i: home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/common.cpp.i
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/common.i

# target to preprocess a source file
home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/common.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/common.cpp.i
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/common.cpp.i

home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/common.s: home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/common.cpp.s
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/common.s

# target to generate assembly for a file
home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/common.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/common.cpp.s
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/common.cpp.s

home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/error.o: home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/error.cpp.o
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/error.o

# target to build an object file
home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/error.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/error.cpp.o
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/error.cpp.o

home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/error.i: home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/error.cpp.i
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/error.i

# target to preprocess a source file
home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/error.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/error.cpp.i
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/error.cpp.i

home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/error.s: home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/error.cpp.s
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/error.s

# target to generate assembly for a file
home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/error.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/error.cpp.s
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/error.cpp.s

home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/implicit.o: home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/implicit.cpp.o
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/implicit.o

# target to build an object file
home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/implicit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/implicit.cpp.o
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/implicit.cpp.o

home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/implicit.i: home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/implicit.cpp.i
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/implicit.i

# target to preprocess a source file
home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/implicit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/implicit.cpp.i
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/implicit.cpp.i

home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/implicit.s: home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/implicit.cpp.s
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/implicit.s

# target to generate assembly for a file
home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/implicit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/implicit.cpp.s
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/implicit.cpp.s

home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_enum.o: home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_enum.cpp.o
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_enum.o

# target to build an object file
home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_enum.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_enum.cpp.o
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_enum.cpp.o

home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_enum.i: home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_enum.cpp.i
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_enum.i

# target to preprocess a source file
home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_enum.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_enum.cpp.i
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_enum.cpp.i

home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_enum.s: home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_enum.cpp.s
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_enum.s

# target to generate assembly for a file
home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_enum.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_enum.cpp.s
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_enum.cpp.s

home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_func.o: home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_func.cpp.o
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_func.o

# target to build an object file
home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_func.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_func.cpp.o
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_func.cpp.o

home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_func.i: home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_func.cpp.i
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_func.i

# target to preprocess a source file
home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_func.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_func.cpp.i
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_func.cpp.i

home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_func.s: home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_func.cpp.s
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_func.s

# target to generate assembly for a file
home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_func.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_func.cpp.s
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_func.cpp.s

home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_internals.o: home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_internals.cpp.o
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_internals.o

# target to build an object file
home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_internals.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_internals.cpp.o
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_internals.cpp.o

home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_internals.i: home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_internals.cpp.i
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_internals.i

# target to preprocess a source file
home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_internals.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_internals.cpp.i
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_internals.cpp.i

home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_internals.s: home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_internals.cpp.s
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_internals.s

# target to generate assembly for a file
home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_internals.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_internals.cpp.s
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_internals.cpp.s

home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_ndarray.o: home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_ndarray.cpp.o
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_ndarray.o

# target to build an object file
home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_ndarray.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_ndarray.cpp.o
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_ndarray.cpp.o

home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_ndarray.i: home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_ndarray.cpp.i
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_ndarray.i

# target to preprocess a source file
home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_ndarray.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_ndarray.cpp.i
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_ndarray.cpp.i

home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_ndarray.s: home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_ndarray.cpp.s
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_ndarray.s

# target to generate assembly for a file
home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_ndarray.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_ndarray.cpp.s
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_ndarray.cpp.s

home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_static_property.o: home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_static_property.cpp.o
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_static_property.o

# target to build an object file
home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_static_property.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_static_property.cpp.o
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_static_property.cpp.o

home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_static_property.i: home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_static_property.cpp.i
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_static_property.i

# target to preprocess a source file
home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_static_property.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_static_property.cpp.i
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_static_property.cpp.i

home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_static_property.s: home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_static_property.cpp.s
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_static_property.s

# target to generate assembly for a file
home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_static_property.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_static_property.cpp.s
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_static_property.cpp.s

home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_type.o: home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_type.cpp.o
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_type.o

# target to build an object file
home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_type.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_type.cpp.o
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_type.cpp.o

home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_type.i: home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_type.cpp.i
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_type.i

# target to preprocess a source file
home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_type.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_type.cpp.i
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_type.cpp.i

home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_type.s: home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_type.cpp.s
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_type.s

# target to generate assembly for a file
home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_type.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_type.cpp.s
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_type.cpp.s

home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/trampoline.o: home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/trampoline.cpp.o
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/trampoline.o

# target to build an object file
home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/trampoline.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/trampoline.cpp.o
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/trampoline.cpp.o

home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/trampoline.i: home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/trampoline.cpp.i
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/trampoline.i

# target to preprocess a source file
home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/trampoline.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/trampoline.cpp.i
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/trampoline.cpp.i

home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/trampoline.s: home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/trampoline.cpp.s
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/trampoline.s

# target to generate assembly for a file
home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/trampoline.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/trampoline.cpp.s
.PHONY : home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/trampoline.cpp.s

src/clustering.o: src/clustering.cpp.o
.PHONY : src/clustering.o

# target to build an object file
src/clustering.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clustering.dir/build.make CMakeFiles/clustering.dir/src/clustering.cpp.o
.PHONY : src/clustering.cpp.o

src/clustering.i: src/clustering.cpp.i
.PHONY : src/clustering.i

# target to preprocess a source file
src/clustering.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clustering.dir/build.make CMakeFiles/clustering.dir/src/clustering.cpp.i
.PHONY : src/clustering.cpp.i

src/clustering.s: src/clustering.cpp.s
.PHONY : src/clustering.s

# target to generate assembly for a file
src/clustering.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clustering.dir/build.make CMakeFiles/clustering.dir/src/clustering.cpp.s
.PHONY : src/clustering.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... clustering"
	@echo "... nanobind-static"
	@echo "... home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/common.o"
	@echo "... home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/common.i"
	@echo "... home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/common.s"
	@echo "... home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/error.o"
	@echo "... home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/error.i"
	@echo "... home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/error.s"
	@echo "... home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/implicit.o"
	@echo "... home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/implicit.i"
	@echo "... home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/implicit.s"
	@echo "... home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_enum.o"
	@echo "... home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_enum.i"
	@echo "... home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_enum.s"
	@echo "... home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_func.o"
	@echo "... home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_func.i"
	@echo "... home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_func.s"
	@echo "... home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_internals.o"
	@echo "... home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_internals.i"
	@echo "... home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_internals.s"
	@echo "... home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_ndarray.o"
	@echo "... home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_ndarray.i"
	@echo "... home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_ndarray.s"
	@echo "... home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_static_property.o"
	@echo "... home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_static_property.i"
	@echo "... home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_static_property.s"
	@echo "... home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_type.o"
	@echo "... home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_type.i"
	@echo "... home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/nb_type.s"
	@echo "... home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/trampoline.o"
	@echo "... home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/trampoline.i"
	@echo "... home/alex/afrl/python/.venv312/lib/python3.12/site-packages/nanobind/src/trampoline.s"
	@echo "... src/clustering.o"
	@echo "... src/clustering.i"
	@echo "... src/clustering.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

